---

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: make
      - run: make int-test
        env:
          MAGIC_SEAWEED_API_KEY: ${{ secrets.MAGIC_SEAWEED_API_KEY }}

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh release create "${{ github.ref_name }}" \
            --generate-notes \
            --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
  bump-index:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://proxy.golang.org/github.com/${{ github.repository }}/@v/${{ github.ref_name }}.info"
